// Code generated by go-swagger; DO NOT EDIT.

package pool_data_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// PoolDataServiceListReader is a Reader for the PoolDataServiceList structure.
type PoolDataServiceListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PoolDataServiceListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPoolDataServiceListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPoolDataServiceListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPoolDataServiceListOK creates a PoolDataServiceListOK with default headers values
func NewPoolDataServiceListOK() *PoolDataServiceListOK {
	return &PoolDataServiceListOK{}
}

/*PoolDataServiceListOK handles this case with default header values.

A successful response.
*/
type PoolDataServiceListOK struct {
	Payload *models.DataListResponse
}

func (o *PoolDataServiceListOK) Error() string {
	return fmt.Sprintf("[GET /api/data/_r/{poolId}][%d] poolDataServiceListOK  %+v", 200, o.Payload)
}

func (o *PoolDataServiceListOK) GetPayload() *models.DataListResponse {
	return o.Payload
}

func (o *PoolDataServiceListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DataListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPoolDataServiceListBadRequest creates a PoolDataServiceListBadRequest with default headers values
func NewPoolDataServiceListBadRequest() *PoolDataServiceListBadRequest {
	return &PoolDataServiceListBadRequest{}
}

/*PoolDataServiceListBadRequest handles this case with default header values.

Returned when input parameters are not provided or correct
*/
type PoolDataServiceListBadRequest struct {
	Payload string
}

func (o *PoolDataServiceListBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/data/_r/{poolId}][%d] poolDataServiceListBadRequest  %+v", 400, o.Payload)
}

func (o *PoolDataServiceListBadRequest) GetPayload() string {
	return o.Payload
}

func (o *PoolDataServiceListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
