// Code generated by go-swagger; DO NOT EDIT.

package pool_data_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// PoolDataServiceBulkUpdateReader is a Reader for the PoolDataServiceBulkUpdate structure.
type PoolDataServiceBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PoolDataServiceBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPoolDataServiceBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPoolDataServiceBulkUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPoolDataServiceBulkUpdateOK creates a PoolDataServiceBulkUpdateOK with default headers values
func NewPoolDataServiceBulkUpdateOK() *PoolDataServiceBulkUpdateOK {
	return &PoolDataServiceBulkUpdateOK{}
}

/*PoolDataServiceBulkUpdateOK handles this case with default header values.

A successful response.
*/
type PoolDataServiceBulkUpdateOK struct {
	Payload *models.DataBulkUpdateResponse
}

func (o *PoolDataServiceBulkUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /api/data/_r/{poolId}][%d] poolDataServiceBulkUpdateOK  %+v", 200, o.Payload)
}

func (o *PoolDataServiceBulkUpdateOK) GetPayload() *models.DataBulkUpdateResponse {
	return o.Payload
}

func (o *PoolDataServiceBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DataBulkUpdateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPoolDataServiceBulkUpdateBadRequest creates a PoolDataServiceBulkUpdateBadRequest with default headers values
func NewPoolDataServiceBulkUpdateBadRequest() *PoolDataServiceBulkUpdateBadRequest {
	return &PoolDataServiceBulkUpdateBadRequest{}
}

/*PoolDataServiceBulkUpdateBadRequest handles this case with default header values.

Returned when input parameters are not provided
*/
type PoolDataServiceBulkUpdateBadRequest struct {
	Payload string
}

func (o *PoolDataServiceBulkUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/data/_r/{poolId}][%d] poolDataServiceBulkUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *PoolDataServiceBulkUpdateBadRequest) GetPayload() string {
	return o.Payload
}

func (o *PoolDataServiceBulkUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
