// Code generated by go-swagger; DO NOT EDIT.

package pool_data_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// PoolDataServiceBulkCreateReader is a Reader for the PoolDataServiceBulkCreate structure.
type PoolDataServiceBulkCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PoolDataServiceBulkCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPoolDataServiceBulkCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPoolDataServiceBulkCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPoolDataServiceBulkCreateOK creates a PoolDataServiceBulkCreateOK with default headers values
func NewPoolDataServiceBulkCreateOK() *PoolDataServiceBulkCreateOK {
	return &PoolDataServiceBulkCreateOK{}
}

/*PoolDataServiceBulkCreateOK handles this case with default header values.

A successful response.
*/
type PoolDataServiceBulkCreateOK struct {
	Payload *models.DataBulkCreateResponse
}

func (o *PoolDataServiceBulkCreateOK) Error() string {
	return fmt.Sprintf("[POST /api/data/_r/{poolId}][%d] poolDataServiceBulkCreateOK  %+v", 200, o.Payload)
}

func (o *PoolDataServiceBulkCreateOK) GetPayload() *models.DataBulkCreateResponse {
	return o.Payload
}

func (o *PoolDataServiceBulkCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DataBulkCreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPoolDataServiceBulkCreateBadRequest creates a PoolDataServiceBulkCreateBadRequest with default headers values
func NewPoolDataServiceBulkCreateBadRequest() *PoolDataServiceBulkCreateBadRequest {
	return &PoolDataServiceBulkCreateBadRequest{}
}

/*PoolDataServiceBulkCreateBadRequest handles this case with default header values.

Returned when input parameters are not provided
*/
type PoolDataServiceBulkCreateBadRequest struct {
	Payload string
}

func (o *PoolDataServiceBulkCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/data/_r/{poolId}][%d] poolDataServiceBulkCreateBadRequest  %+v", 400, o.Payload)
}

func (o *PoolDataServiceBulkCreateBadRequest) GetPayload() string {
	return o.Payload
}

func (o *PoolDataServiceBulkCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
