// Code generated by go-swagger; DO NOT EDIT.

package functions_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// FunctionsServiceUpdateFunction2Reader is a Reader for the FunctionsServiceUpdateFunction2 structure.
type FunctionsServiceUpdateFunction2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FunctionsServiceUpdateFunction2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFunctionsServiceUpdateFunction2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewFunctionsServiceUpdateFunction2NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewFunctionsServiceUpdateFunction2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFunctionsServiceUpdateFunction2OK creates a FunctionsServiceUpdateFunction2OK with default headers values
func NewFunctionsServiceUpdateFunction2OK() *FunctionsServiceUpdateFunction2OK {
	return &FunctionsServiceUpdateFunction2OK{}
}

/* FunctionsServiceUpdateFunction2OK describes a response with status code 200, with default header values.

A successful response.
*/
type FunctionsServiceUpdateFunction2OK struct {
	Payload models.FunctionsUpdateFunctionResponse
}

func (o *FunctionsServiceUpdateFunction2OK) Error() string {
	return fmt.Sprintf("[PATCH /api/func/v1/function/{function.id}][%d] functionsServiceUpdateFunction2OK  %+v", 200, o.Payload)
}
func (o *FunctionsServiceUpdateFunction2OK) GetPayload() models.FunctionsUpdateFunctionResponse {
	return o.Payload
}

func (o *FunctionsServiceUpdateFunction2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFunctionsServiceUpdateFunction2NotFound creates a FunctionsServiceUpdateFunction2NotFound with default headers values
func NewFunctionsServiceUpdateFunction2NotFound() *FunctionsServiceUpdateFunction2NotFound {
	return &FunctionsServiceUpdateFunction2NotFound{}
}

/* FunctionsServiceUpdateFunction2NotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type FunctionsServiceUpdateFunction2NotFound struct {
	Payload string
}

func (o *FunctionsServiceUpdateFunction2NotFound) Error() string {
	return fmt.Sprintf("[PATCH /api/func/v1/function/{function.id}][%d] functionsServiceUpdateFunction2NotFound  %+v", 404, o.Payload)
}
func (o *FunctionsServiceUpdateFunction2NotFound) GetPayload() string {
	return o.Payload
}

func (o *FunctionsServiceUpdateFunction2NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFunctionsServiceUpdateFunction2Default creates a FunctionsServiceUpdateFunction2Default with default headers values
func NewFunctionsServiceUpdateFunction2Default(code int) *FunctionsServiceUpdateFunction2Default {
	return &FunctionsServiceUpdateFunction2Default{
		_statusCode: code,
	}
}

/* FunctionsServiceUpdateFunction2Default describes a response with status code -1, with default header values.

An unexpected error response
*/
type FunctionsServiceUpdateFunction2Default struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the functions service update function2 default response
func (o *FunctionsServiceUpdateFunction2Default) Code() int {
	return o._statusCode
}

func (o *FunctionsServiceUpdateFunction2Default) Error() string {
	return fmt.Sprintf("[PATCH /api/func/v1/function/{function.id}][%d] FunctionsService_UpdateFunction2 default  %+v", o._statusCode, o.Payload)
}
func (o *FunctionsServiceUpdateFunction2Default) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *FunctionsServiceUpdateFunction2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
