/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// V1UpdateUserRequest struct for V1UpdateUserRequest
type V1UpdateUserRequest struct {
	User V1User `json:"user,omitempty"`
}
