/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FunctionsFunction struct for FunctionsFunction
type FunctionsFunction struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	FuncType string `json:"funcType,omitempty"`
	Endpoint string `json:"endpoint,omitempty"`
	Region string `json:"region,omitempty"`
}
