/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DistrconfigUnassignPoolsFromAppRequest struct for DistrconfigUnassignPoolsFromAppRequest
type DistrconfigUnassignPoolsFromAppRequest struct {
	AppID string `json:"appID,omitempty"`
	PoolIDs []string `json:"poolIDs,omitempty"`
}
