/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AccountAccountStatus the model 'AccountAccountStatus'
type AccountAccountStatus string

// List of AccountAccountStatus
const (
	PENDING AccountAccountStatus = "PENDING"
	ACTIVE AccountAccountStatus = "ACTIVE"
	DISABLED AccountAccountStatus = "DISABLED"
	DELETED AccountAccountStatus = "DELETED"
)
