/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// V1UpdateRoleRequest struct for V1UpdateRoleRequest
type V1UpdateRoleRequest struct {
	Role V1Role `json:"role,omitempty"`
}
