/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// V1SetPasswordRequest struct for V1SetPasswordRequest
type V1SetPasswordRequest struct {
	UserID string `json:"userID,omitempty"`
	UserPassword string `json:"userPassword,omitempty"`
	NewPassword string `json:"newPassword,omitempty"`
}
