/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DistrconfigGetAppResponse struct for DistrconfigGetAppResponse
type DistrconfigGetAppResponse struct {
	App DistrconfigMobileAppWithPools `json:"app,omitempty"`
}
