/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FunctionsCallFunctionResponse struct for FunctionsCallFunctionResponse
type FunctionsCallFunctionResponse struct {
	Success bool `json:"success,omitempty"`
	Err string `json:"err,omitempty"`
	Body map[string]interface{} `json:"body,omitempty"`
}
