/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DistrconfigPoolSize struct for DistrconfigPoolSize
type DistrconfigPoolSize struct {
	PoolId string `json:"poolId,omitempty"`
	GlobalDataSizeBytes string `json:"globalDataSizeBytes,omitempty"`
	UserDataSizeBytes string `json:"userDataSizeBytes,omitempty"`
}
