/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// V1CreatePolicyRequest struct for V1CreatePolicyRequest
type V1CreatePolicyRequest struct {
	Policy V1Policy `json:"policy,omitempty"`
}
