/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// V1PasswordPolicy struct for V1PasswordPolicy
type V1PasswordPolicy struct {
	MinLength string `json:"minLength,omitempty"`
	UseLowerLetters bool `json:"useLowerLetters,omitempty"`
	UseUpperLetters bool `json:"useUpperLetters,omitempty"`
	UseNumbers bool `json:"useNumbers,omitempty"`
	UseSpecialCharecters bool `json:"useSpecialCharecters,omitempty"`
}
