/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DistrconfigPoolType the model 'DistrconfigPoolType'
type DistrconfigPoolType string

// List of distrconfigPoolType
const (
	UNKNOWN DistrconfigPoolType = "UNKNOWN"
	GLOBAL DistrconfigPoolType = "GLOBAL"
	FILTERED DistrconfigPoolType = "FILTERED"
	USER DistrconfigPoolType = "USER"
)
