/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// V1CreatePolicyResponse struct for V1CreatePolicyResponse
type V1CreatePolicyResponse struct {
	PolicyID string `json:"policyID,omitempty"`
}
