/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// V1CreateUserResponse struct for V1CreateUserResponse
type V1CreateUserResponse struct {
	UserID string `json:"userID,omitempty"`
}
