/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DataBulkDeleteResponse struct for DataBulkDeleteResponse
type DataBulkDeleteResponse struct {
	// Successful deletion
	Result []DataPersistResponse `json:"result,omitempty"`
	// List of errors if any occur
	Errors []string `json:"errors,omitempty"`
}
