/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// V1RemovePoliciesFromRoleRequest struct for V1RemovePoliciesFromRoleRequest
type V1RemovePoliciesFromRoleRequest struct {
	RoleID string `json:"roleID,omitempty"`
	PolicyIDs []string `json:"policyIDs,omitempty"`
}
