/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// V1Role struct for V1Role
type V1Role struct {
	RoleID string `json:"roleID,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	PolicyIDs []string `json:"policyIDs,omitempty"`
}
