/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FunctionsCallFunctionRequest struct for FunctionsCallFunctionRequest
type FunctionsCallFunctionRequest struct {
	Id string `json:"id,omitempty"`
	Payload map[string]interface{} `json:"payload,omitempty"`
	PayloadJSON string `json:"payloadJSON,omitempty"`
}
