/*
 * Zest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: contact@zestlabs.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FunctionsGetFunctionsResponse struct for FunctionsGetFunctionsResponse
type FunctionsGetFunctionsResponse struct {
	Functions []FunctionsFunction `json:"functions,omitempty"`
}
