// Code generated by go-swagger; DO NOT EDIT.

package distr_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// NewDistrConfigServiceCreateAppParams creates a new DistrConfigServiceCreateAppParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDistrConfigServiceCreateAppParams() *DistrConfigServiceCreateAppParams {
	return &DistrConfigServiceCreateAppParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDistrConfigServiceCreateAppParamsWithTimeout creates a new DistrConfigServiceCreateAppParams object
// with the ability to set a timeout on a request.
func NewDistrConfigServiceCreateAppParamsWithTimeout(timeout time.Duration) *DistrConfigServiceCreateAppParams {
	return &DistrConfigServiceCreateAppParams{
		timeout: timeout,
	}
}

// NewDistrConfigServiceCreateAppParamsWithContext creates a new DistrConfigServiceCreateAppParams object
// with the ability to set a context for a request.
func NewDistrConfigServiceCreateAppParamsWithContext(ctx context.Context) *DistrConfigServiceCreateAppParams {
	return &DistrConfigServiceCreateAppParams{
		Context: ctx,
	}
}

// NewDistrConfigServiceCreateAppParamsWithHTTPClient creates a new DistrConfigServiceCreateAppParams object
// with the ability to set a custom HTTPClient for a request.
func NewDistrConfigServiceCreateAppParamsWithHTTPClient(client *http.Client) *DistrConfigServiceCreateAppParams {
	return &DistrConfigServiceCreateAppParams{
		HTTPClient: client,
	}
}

/* DistrConfigServiceCreateAppParams contains all the parameters to send to the API endpoint
   for the distr config service create app operation.

   Typically these are written to a http.Request.
*/
type DistrConfigServiceCreateAppParams struct {

	// Body.
	Body *models.DistrconfigMobileApp

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the distr config service create app params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DistrConfigServiceCreateAppParams) WithDefaults() *DistrConfigServiceCreateAppParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the distr config service create app params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DistrConfigServiceCreateAppParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the distr config service create app params
func (o *DistrConfigServiceCreateAppParams) WithTimeout(timeout time.Duration) *DistrConfigServiceCreateAppParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the distr config service create app params
func (o *DistrConfigServiceCreateAppParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the distr config service create app params
func (o *DistrConfigServiceCreateAppParams) WithContext(ctx context.Context) *DistrConfigServiceCreateAppParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the distr config service create app params
func (o *DistrConfigServiceCreateAppParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the distr config service create app params
func (o *DistrConfigServiceCreateAppParams) WithHTTPClient(client *http.Client) *DistrConfigServiceCreateAppParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the distr config service create app params
func (o *DistrConfigServiceCreateAppParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the distr config service create app params
func (o *DistrConfigServiceCreateAppParams) WithBody(body *models.DistrconfigMobileApp) *DistrConfigServiceCreateAppParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the distr config service create app params
func (o *DistrConfigServiceCreateAppParams) SetBody(body *models.DistrconfigMobileApp) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DistrConfigServiceCreateAppParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
