// Code generated by go-swagger; DO NOT EDIT.

package distr_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// DistrConfigServiceGetUserReader is a Reader for the DistrConfigServiceGetUser structure.
type DistrConfigServiceGetUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DistrConfigServiceGetUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDistrConfigServiceGetUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDistrConfigServiceGetUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDistrConfigServiceGetUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDistrConfigServiceGetUserOK creates a DistrConfigServiceGetUserOK with default headers values
func NewDistrConfigServiceGetUserOK() *DistrConfigServiceGetUserOK {
	return &DistrConfigServiceGetUserOK{}
}

/* DistrConfigServiceGetUserOK describes a response with status code 200, with default header values.

A successful response.
*/
type DistrConfigServiceGetUserOK struct {
	Payload *models.DistrconfigGetUserResponse
}

func (o *DistrConfigServiceGetUserOK) Error() string {
	return fmt.Sprintf("[GET /api/distribution/v1/user/{userID}][%d] distrConfigServiceGetUserOK  %+v", 200, o.Payload)
}
func (o *DistrConfigServiceGetUserOK) GetPayload() *models.DistrconfigGetUserResponse {
	return o.Payload
}

func (o *DistrConfigServiceGetUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DistrconfigGetUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDistrConfigServiceGetUserNotFound creates a DistrConfigServiceGetUserNotFound with default headers values
func NewDistrConfigServiceGetUserNotFound() *DistrConfigServiceGetUserNotFound {
	return &DistrConfigServiceGetUserNotFound{}
}

/* DistrConfigServiceGetUserNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type DistrConfigServiceGetUserNotFound struct {
	Payload string
}

func (o *DistrConfigServiceGetUserNotFound) Error() string {
	return fmt.Sprintf("[GET /api/distribution/v1/user/{userID}][%d] distrConfigServiceGetUserNotFound  %+v", 404, o.Payload)
}
func (o *DistrConfigServiceGetUserNotFound) GetPayload() string {
	return o.Payload
}

func (o *DistrConfigServiceGetUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDistrConfigServiceGetUserDefault creates a DistrConfigServiceGetUserDefault with default headers values
func NewDistrConfigServiceGetUserDefault(code int) *DistrConfigServiceGetUserDefault {
	return &DistrConfigServiceGetUserDefault{
		_statusCode: code,
	}
}

/* DistrConfigServiceGetUserDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type DistrConfigServiceGetUserDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the distr config service get user default response
func (o *DistrConfigServiceGetUserDefault) Code() int {
	return o._statusCode
}

func (o *DistrConfigServiceGetUserDefault) Error() string {
	return fmt.Sprintf("[GET /api/distribution/v1/user/{userID}][%d] DistrConfigService_GetUser default  %+v", o._statusCode, o.Payload)
}
func (o *DistrConfigServiceGetUserDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *DistrConfigServiceGetUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
