// Code generated by go-swagger; DO NOT EDIT.

package distr_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// DistrConfigServiceGetAppsReader is a Reader for the DistrConfigServiceGetApps structure.
type DistrConfigServiceGetAppsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DistrConfigServiceGetAppsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDistrConfigServiceGetAppsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDistrConfigServiceGetAppsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDistrConfigServiceGetAppsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDistrConfigServiceGetAppsOK creates a DistrConfigServiceGetAppsOK with default headers values
func NewDistrConfigServiceGetAppsOK() *DistrConfigServiceGetAppsOK {
	return &DistrConfigServiceGetAppsOK{}
}

/*DistrConfigServiceGetAppsOK handles this case with default header values.

A successful response.
*/
type DistrConfigServiceGetAppsOK struct {
	Payload *models.DistrconfigGetAppsResponse
}

func (o *DistrConfigServiceGetAppsOK) Error() string {
	return fmt.Sprintf("[GET /api/distribution/v1/apps][%d] distrConfigServiceGetAppsOK  %+v", 200, o.Payload)
}

func (o *DistrConfigServiceGetAppsOK) GetPayload() *models.DistrconfigGetAppsResponse {
	return o.Payload
}

func (o *DistrConfigServiceGetAppsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DistrconfigGetAppsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDistrConfigServiceGetAppsNotFound creates a DistrConfigServiceGetAppsNotFound with default headers values
func NewDistrConfigServiceGetAppsNotFound() *DistrConfigServiceGetAppsNotFound {
	return &DistrConfigServiceGetAppsNotFound{}
}

/*DistrConfigServiceGetAppsNotFound handles this case with default header values.

Returned when the resource does not exist.
*/
type DistrConfigServiceGetAppsNotFound struct {
	Payload string
}

func (o *DistrConfigServiceGetAppsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/distribution/v1/apps][%d] distrConfigServiceGetAppsNotFound  %+v", 404, o.Payload)
}

func (o *DistrConfigServiceGetAppsNotFound) GetPayload() string {
	return o.Payload
}

func (o *DistrConfigServiceGetAppsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDistrConfigServiceGetAppsDefault creates a DistrConfigServiceGetAppsDefault with default headers values
func NewDistrConfigServiceGetAppsDefault(code int) *DistrConfigServiceGetAppsDefault {
	return &DistrConfigServiceGetAppsDefault{
		_statusCode: code,
	}
}

/*DistrConfigServiceGetAppsDefault handles this case with default header values.

An unexpected error response
*/
type DistrConfigServiceGetAppsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the distr config service get apps default response
func (o *DistrConfigServiceGetAppsDefault) Code() int {
	return o._statusCode
}

func (o *DistrConfigServiceGetAppsDefault) Error() string {
	return fmt.Sprintf("[GET /api/distribution/v1/apps][%d] DistrConfigService_GetApps default  %+v", o._statusCode, o.Payload)
}

func (o *DistrConfigServiceGetAppsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *DistrConfigServiceGetAppsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
