// Code generated by go-swagger; DO NOT EDIT.

package distr_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// NewDistrConfigServiceCreateUserParams creates a new DistrConfigServiceCreateUserParams object
// with the default values initialized.
func NewDistrConfigServiceCreateUserParams() *DistrConfigServiceCreateUserParams {
	var ()
	return &DistrConfigServiceCreateUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDistrConfigServiceCreateUserParamsWithTimeout creates a new DistrConfigServiceCreateUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDistrConfigServiceCreateUserParamsWithTimeout(timeout time.Duration) *DistrConfigServiceCreateUserParams {
	var ()
	return &DistrConfigServiceCreateUserParams{

		timeout: timeout,
	}
}

// NewDistrConfigServiceCreateUserParamsWithContext creates a new DistrConfigServiceCreateUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewDistrConfigServiceCreateUserParamsWithContext(ctx context.Context) *DistrConfigServiceCreateUserParams {
	var ()
	return &DistrConfigServiceCreateUserParams{

		Context: ctx,
	}
}

// NewDistrConfigServiceCreateUserParamsWithHTTPClient creates a new DistrConfigServiceCreateUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDistrConfigServiceCreateUserParamsWithHTTPClient(client *http.Client) *DistrConfigServiceCreateUserParams {
	var ()
	return &DistrConfigServiceCreateUserParams{
		HTTPClient: client,
	}
}

/*DistrConfigServiceCreateUserParams contains all the parameters to send to the API endpoint
for the distr config service create user operation typically these are written to a http.Request
*/
type DistrConfigServiceCreateUserParams struct {

	/*Body*/
	Body *models.DistrconfigCreateUserRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the distr config service create user params
func (o *DistrConfigServiceCreateUserParams) WithTimeout(timeout time.Duration) *DistrConfigServiceCreateUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the distr config service create user params
func (o *DistrConfigServiceCreateUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the distr config service create user params
func (o *DistrConfigServiceCreateUserParams) WithContext(ctx context.Context) *DistrConfigServiceCreateUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the distr config service create user params
func (o *DistrConfigServiceCreateUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the distr config service create user params
func (o *DistrConfigServiceCreateUserParams) WithHTTPClient(client *http.Client) *DistrConfigServiceCreateUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the distr config service create user params
func (o *DistrConfigServiceCreateUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the distr config service create user params
func (o *DistrConfigServiceCreateUserParams) WithBody(body *models.DistrconfigCreateUserRequest) *DistrConfigServiceCreateUserParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the distr config service create user params
func (o *DistrConfigServiceCreateUserParams) SetBody(body *models.DistrconfigCreateUserRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DistrConfigServiceCreateUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
