// Code generated by go-swagger; DO NOT EDIT.

package distr_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDistrConfigServiceDeletePoolParams creates a new DistrConfigServiceDeletePoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDistrConfigServiceDeletePoolParams() *DistrConfigServiceDeletePoolParams {
	return &DistrConfigServiceDeletePoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDistrConfigServiceDeletePoolParamsWithTimeout creates a new DistrConfigServiceDeletePoolParams object
// with the ability to set a timeout on a request.
func NewDistrConfigServiceDeletePoolParamsWithTimeout(timeout time.Duration) *DistrConfigServiceDeletePoolParams {
	return &DistrConfigServiceDeletePoolParams{
		timeout: timeout,
	}
}

// NewDistrConfigServiceDeletePoolParamsWithContext creates a new DistrConfigServiceDeletePoolParams object
// with the ability to set a context for a request.
func NewDistrConfigServiceDeletePoolParamsWithContext(ctx context.Context) *DistrConfigServiceDeletePoolParams {
	return &DistrConfigServiceDeletePoolParams{
		Context: ctx,
	}
}

// NewDistrConfigServiceDeletePoolParamsWithHTTPClient creates a new DistrConfigServiceDeletePoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewDistrConfigServiceDeletePoolParamsWithHTTPClient(client *http.Client) *DistrConfigServiceDeletePoolParams {
	return &DistrConfigServiceDeletePoolParams{
		HTTPClient: client,
	}
}

/* DistrConfigServiceDeletePoolParams contains all the parameters to send to the API endpoint
   for the distr config service delete pool operation.

   Typically these are written to a http.Request.
*/
type DistrConfigServiceDeletePoolParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the distr config service delete pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DistrConfigServiceDeletePoolParams) WithDefaults() *DistrConfigServiceDeletePoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the distr config service delete pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DistrConfigServiceDeletePoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the distr config service delete pool params
func (o *DistrConfigServiceDeletePoolParams) WithTimeout(timeout time.Duration) *DistrConfigServiceDeletePoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the distr config service delete pool params
func (o *DistrConfigServiceDeletePoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the distr config service delete pool params
func (o *DistrConfigServiceDeletePoolParams) WithContext(ctx context.Context) *DistrConfigServiceDeletePoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the distr config service delete pool params
func (o *DistrConfigServiceDeletePoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the distr config service delete pool params
func (o *DistrConfigServiceDeletePoolParams) WithHTTPClient(client *http.Client) *DistrConfigServiceDeletePoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the distr config service delete pool params
func (o *DistrConfigServiceDeletePoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the distr config service delete pool params
func (o *DistrConfigServiceDeletePoolParams) WithID(id string) *DistrConfigServiceDeletePoolParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the distr config service delete pool params
func (o *DistrConfigServiceDeletePoolParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DistrConfigServiceDeletePoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
