// Code generated by go-swagger; DO NOT EDIT.

package distr_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// DistrConfigServiceGetUsersReader is a Reader for the DistrConfigServiceGetUsers structure.
type DistrConfigServiceGetUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DistrConfigServiceGetUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDistrConfigServiceGetUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDistrConfigServiceGetUsersNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDistrConfigServiceGetUsersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDistrConfigServiceGetUsersOK creates a DistrConfigServiceGetUsersOK with default headers values
func NewDistrConfigServiceGetUsersOK() *DistrConfigServiceGetUsersOK {
	return &DistrConfigServiceGetUsersOK{}
}

/*DistrConfigServiceGetUsersOK handles this case with default header values.

A successful response.
*/
type DistrConfigServiceGetUsersOK struct {
	Payload *models.DistrconfigGetUsersResponse
}

func (o *DistrConfigServiceGetUsersOK) Error() string {
	return fmt.Sprintf("[GET /api/distribution/v1/users][%d] distrConfigServiceGetUsersOK  %+v", 200, o.Payload)
}

func (o *DistrConfigServiceGetUsersOK) GetPayload() *models.DistrconfigGetUsersResponse {
	return o.Payload
}

func (o *DistrConfigServiceGetUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DistrconfigGetUsersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDistrConfigServiceGetUsersNotFound creates a DistrConfigServiceGetUsersNotFound with default headers values
func NewDistrConfigServiceGetUsersNotFound() *DistrConfigServiceGetUsersNotFound {
	return &DistrConfigServiceGetUsersNotFound{}
}

/*DistrConfigServiceGetUsersNotFound handles this case with default header values.

Returned when the resource does not exist.
*/
type DistrConfigServiceGetUsersNotFound struct {
	Payload string
}

func (o *DistrConfigServiceGetUsersNotFound) Error() string {
	return fmt.Sprintf("[GET /api/distribution/v1/users][%d] distrConfigServiceGetUsersNotFound  %+v", 404, o.Payload)
}

func (o *DistrConfigServiceGetUsersNotFound) GetPayload() string {
	return o.Payload
}

func (o *DistrConfigServiceGetUsersNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDistrConfigServiceGetUsersDefault creates a DistrConfigServiceGetUsersDefault with default headers values
func NewDistrConfigServiceGetUsersDefault(code int) *DistrConfigServiceGetUsersDefault {
	return &DistrConfigServiceGetUsersDefault{
		_statusCode: code,
	}
}

/*DistrConfigServiceGetUsersDefault handles this case with default header values.

An unexpected error response
*/
type DistrConfigServiceGetUsersDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the distr config service get users default response
func (o *DistrConfigServiceGetUsersDefault) Code() int {
	return o._statusCode
}

func (o *DistrConfigServiceGetUsersDefault) Error() string {
	return fmt.Sprintf("[GET /api/distribution/v1/users][%d] DistrConfigService_GetUsers default  %+v", o._statusCode, o.Payload)
}

func (o *DistrConfigServiceGetUsersDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *DistrConfigServiceGetUsersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
