// Code generated by go-swagger; DO NOT EDIT.

package distr_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// NewDistrConfigServiceUnassignTagFromUserParams creates a new DistrConfigServiceUnassignTagFromUserParams object
// with the default values initialized.
func NewDistrConfigServiceUnassignTagFromUserParams() *DistrConfigServiceUnassignTagFromUserParams {
	var ()
	return &DistrConfigServiceUnassignTagFromUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDistrConfigServiceUnassignTagFromUserParamsWithTimeout creates a new DistrConfigServiceUnassignTagFromUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDistrConfigServiceUnassignTagFromUserParamsWithTimeout(timeout time.Duration) *DistrConfigServiceUnassignTagFromUserParams {
	var ()
	return &DistrConfigServiceUnassignTagFromUserParams{

		timeout: timeout,
	}
}

// NewDistrConfigServiceUnassignTagFromUserParamsWithContext creates a new DistrConfigServiceUnassignTagFromUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewDistrConfigServiceUnassignTagFromUserParamsWithContext(ctx context.Context) *DistrConfigServiceUnassignTagFromUserParams {
	var ()
	return &DistrConfigServiceUnassignTagFromUserParams{

		Context: ctx,
	}
}

// NewDistrConfigServiceUnassignTagFromUserParamsWithHTTPClient creates a new DistrConfigServiceUnassignTagFromUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDistrConfigServiceUnassignTagFromUserParamsWithHTTPClient(client *http.Client) *DistrConfigServiceUnassignTagFromUserParams {
	var ()
	return &DistrConfigServiceUnassignTagFromUserParams{
		HTTPClient: client,
	}
}

/*DistrConfigServiceUnassignTagFromUserParams contains all the parameters to send to the API endpoint
for the distr config service unassign tag from user operation typically these are written to a http.Request
*/
type DistrConfigServiceUnassignTagFromUserParams struct {

	/*Body*/
	Body *models.DistrconfigUnassignTagFromUserRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the distr config service unassign tag from user params
func (o *DistrConfigServiceUnassignTagFromUserParams) WithTimeout(timeout time.Duration) *DistrConfigServiceUnassignTagFromUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the distr config service unassign tag from user params
func (o *DistrConfigServiceUnassignTagFromUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the distr config service unassign tag from user params
func (o *DistrConfigServiceUnassignTagFromUserParams) WithContext(ctx context.Context) *DistrConfigServiceUnassignTagFromUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the distr config service unassign tag from user params
func (o *DistrConfigServiceUnassignTagFromUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the distr config service unassign tag from user params
func (o *DistrConfigServiceUnassignTagFromUserParams) WithHTTPClient(client *http.Client) *DistrConfigServiceUnassignTagFromUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the distr config service unassign tag from user params
func (o *DistrConfigServiceUnassignTagFromUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the distr config service unassign tag from user params
func (o *DistrConfigServiceUnassignTagFromUserParams) WithBody(body *models.DistrconfigUnassignTagFromUserRequest) *DistrConfigServiceUnassignTagFromUserParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the distr config service unassign tag from user params
func (o *DistrConfigServiceUnassignTagFromUserParams) SetBody(body *models.DistrconfigUnassignTagFromUserRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DistrConfigServiceUnassignTagFromUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
