// Code generated by go-swagger; DO NOT EDIT.

package distr_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDistrConfigServiceGetUsersParams creates a new DistrConfigServiceGetUsersParams object
// with the default values initialized.
func NewDistrConfigServiceGetUsersParams() *DistrConfigServiceGetUsersParams {

	return &DistrConfigServiceGetUsersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDistrConfigServiceGetUsersParamsWithTimeout creates a new DistrConfigServiceGetUsersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDistrConfigServiceGetUsersParamsWithTimeout(timeout time.Duration) *DistrConfigServiceGetUsersParams {

	return &DistrConfigServiceGetUsersParams{

		timeout: timeout,
	}
}

// NewDistrConfigServiceGetUsersParamsWithContext creates a new DistrConfigServiceGetUsersParams object
// with the default values initialized, and the ability to set a context for a request
func NewDistrConfigServiceGetUsersParamsWithContext(ctx context.Context) *DistrConfigServiceGetUsersParams {

	return &DistrConfigServiceGetUsersParams{

		Context: ctx,
	}
}

// NewDistrConfigServiceGetUsersParamsWithHTTPClient creates a new DistrConfigServiceGetUsersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDistrConfigServiceGetUsersParamsWithHTTPClient(client *http.Client) *DistrConfigServiceGetUsersParams {

	return &DistrConfigServiceGetUsersParams{
		HTTPClient: client,
	}
}

/*DistrConfigServiceGetUsersParams contains all the parameters to send to the API endpoint
for the distr config service get users operation typically these are written to a http.Request
*/
type DistrConfigServiceGetUsersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the distr config service get users params
func (o *DistrConfigServiceGetUsersParams) WithTimeout(timeout time.Duration) *DistrConfigServiceGetUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the distr config service get users params
func (o *DistrConfigServiceGetUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the distr config service get users params
func (o *DistrConfigServiceGetUsersParams) WithContext(ctx context.Context) *DistrConfigServiceGetUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the distr config service get users params
func (o *DistrConfigServiceGetUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the distr config service get users params
func (o *DistrConfigServiceGetUsersParams) WithHTTPClient(client *http.Client) *DistrConfigServiceGetUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the distr config service get users params
func (o *DistrConfigServiceGetUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DistrConfigServiceGetUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
