// Code generated by go-swagger; DO NOT EDIT.

package distr_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// NewDistrConfigServiceAssignPoolsToAppParams creates a new DistrConfigServiceAssignPoolsToAppParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDistrConfigServiceAssignPoolsToAppParams() *DistrConfigServiceAssignPoolsToAppParams {
	return &DistrConfigServiceAssignPoolsToAppParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDistrConfigServiceAssignPoolsToAppParamsWithTimeout creates a new DistrConfigServiceAssignPoolsToAppParams object
// with the ability to set a timeout on a request.
func NewDistrConfigServiceAssignPoolsToAppParamsWithTimeout(timeout time.Duration) *DistrConfigServiceAssignPoolsToAppParams {
	return &DistrConfigServiceAssignPoolsToAppParams{
		timeout: timeout,
	}
}

// NewDistrConfigServiceAssignPoolsToAppParamsWithContext creates a new DistrConfigServiceAssignPoolsToAppParams object
// with the ability to set a context for a request.
func NewDistrConfigServiceAssignPoolsToAppParamsWithContext(ctx context.Context) *DistrConfigServiceAssignPoolsToAppParams {
	return &DistrConfigServiceAssignPoolsToAppParams{
		Context: ctx,
	}
}

// NewDistrConfigServiceAssignPoolsToAppParamsWithHTTPClient creates a new DistrConfigServiceAssignPoolsToAppParams object
// with the ability to set a custom HTTPClient for a request.
func NewDistrConfigServiceAssignPoolsToAppParamsWithHTTPClient(client *http.Client) *DistrConfigServiceAssignPoolsToAppParams {
	return &DistrConfigServiceAssignPoolsToAppParams{
		HTTPClient: client,
	}
}

/* DistrConfigServiceAssignPoolsToAppParams contains all the parameters to send to the API endpoint
   for the distr config service assign pools to app operation.

   Typically these are written to a http.Request.
*/
type DistrConfigServiceAssignPoolsToAppParams struct {

	// Body.
	Body *models.DistrconfigAssignPoolsToAppRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the distr config service assign pools to app params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DistrConfigServiceAssignPoolsToAppParams) WithDefaults() *DistrConfigServiceAssignPoolsToAppParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the distr config service assign pools to app params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DistrConfigServiceAssignPoolsToAppParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the distr config service assign pools to app params
func (o *DistrConfigServiceAssignPoolsToAppParams) WithTimeout(timeout time.Duration) *DistrConfigServiceAssignPoolsToAppParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the distr config service assign pools to app params
func (o *DistrConfigServiceAssignPoolsToAppParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the distr config service assign pools to app params
func (o *DistrConfigServiceAssignPoolsToAppParams) WithContext(ctx context.Context) *DistrConfigServiceAssignPoolsToAppParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the distr config service assign pools to app params
func (o *DistrConfigServiceAssignPoolsToAppParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the distr config service assign pools to app params
func (o *DistrConfigServiceAssignPoolsToAppParams) WithHTTPClient(client *http.Client) *DistrConfigServiceAssignPoolsToAppParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the distr config service assign pools to app params
func (o *DistrConfigServiceAssignPoolsToAppParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the distr config service assign pools to app params
func (o *DistrConfigServiceAssignPoolsToAppParams) WithBody(body *models.DistrconfigAssignPoolsToAppRequest) *DistrConfigServiceAssignPoolsToAppParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the distr config service assign pools to app params
func (o *DistrConfigServiceAssignPoolsToAppParams) SetBody(body *models.DistrconfigAssignPoolsToAppRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DistrConfigServiceAssignPoolsToAppParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
