// Code generated by go-swagger; DO NOT EDIT.

package distr_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDistrConfigServiceGetPoolDistributionParams creates a new DistrConfigServiceGetPoolDistributionParams object
// with the default values initialized.
func NewDistrConfigServiceGetPoolDistributionParams() *DistrConfigServiceGetPoolDistributionParams {
	var ()
	return &DistrConfigServiceGetPoolDistributionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDistrConfigServiceGetPoolDistributionParamsWithTimeout creates a new DistrConfigServiceGetPoolDistributionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDistrConfigServiceGetPoolDistributionParamsWithTimeout(timeout time.Duration) *DistrConfigServiceGetPoolDistributionParams {
	var ()
	return &DistrConfigServiceGetPoolDistributionParams{

		timeout: timeout,
	}
}

// NewDistrConfigServiceGetPoolDistributionParamsWithContext creates a new DistrConfigServiceGetPoolDistributionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDistrConfigServiceGetPoolDistributionParamsWithContext(ctx context.Context) *DistrConfigServiceGetPoolDistributionParams {
	var ()
	return &DistrConfigServiceGetPoolDistributionParams{

		Context: ctx,
	}
}

// NewDistrConfigServiceGetPoolDistributionParamsWithHTTPClient creates a new DistrConfigServiceGetPoolDistributionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDistrConfigServiceGetPoolDistributionParamsWithHTTPClient(client *http.Client) *DistrConfigServiceGetPoolDistributionParams {
	var ()
	return &DistrConfigServiceGetPoolDistributionParams{
		HTTPClient: client,
	}
}

/*DistrConfigServiceGetPoolDistributionParams contains all the parameters to send to the API endpoint
for the distr config service get pool distribution operation typically these are written to a http.Request
*/
type DistrConfigServiceGetPoolDistributionParams struct {

	/*ID*/
	ID string
	/*UserID*/
	UserID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the distr config service get pool distribution params
func (o *DistrConfigServiceGetPoolDistributionParams) WithTimeout(timeout time.Duration) *DistrConfigServiceGetPoolDistributionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the distr config service get pool distribution params
func (o *DistrConfigServiceGetPoolDistributionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the distr config service get pool distribution params
func (o *DistrConfigServiceGetPoolDistributionParams) WithContext(ctx context.Context) *DistrConfigServiceGetPoolDistributionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the distr config service get pool distribution params
func (o *DistrConfigServiceGetPoolDistributionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the distr config service get pool distribution params
func (o *DistrConfigServiceGetPoolDistributionParams) WithHTTPClient(client *http.Client) *DistrConfigServiceGetPoolDistributionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the distr config service get pool distribution params
func (o *DistrConfigServiceGetPoolDistributionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the distr config service get pool distribution params
func (o *DistrConfigServiceGetPoolDistributionParams) WithID(id string) *DistrConfigServiceGetPoolDistributionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the distr config service get pool distribution params
func (o *DistrConfigServiceGetPoolDistributionParams) SetID(id string) {
	o.ID = id
}

// WithUserID adds the userID to the distr config service get pool distribution params
func (o *DistrConfigServiceGetPoolDistributionParams) WithUserID(userID *string) *DistrConfigServiceGetPoolDistributionParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the distr config service get pool distribution params
func (o *DistrConfigServiceGetPoolDistributionParams) SetUserID(userID *string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *DistrConfigServiceGetPoolDistributionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.UserID != nil {

		// query param userId
		var qrUserID string
		if o.UserID != nil {
			qrUserID = *o.UserID
		}
		qUserID := qrUserID
		if qUserID != "" {
			if err := r.SetQueryParam("userId", qUserID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
