// Code generated by go-swagger; DO NOT EDIT.

package distr_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDistrConfigServiceGetPoolsParams creates a new DistrConfigServiceGetPoolsParams object
// with the default values initialized.
func NewDistrConfigServiceGetPoolsParams() *DistrConfigServiceGetPoolsParams {

	return &DistrConfigServiceGetPoolsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDistrConfigServiceGetPoolsParamsWithTimeout creates a new DistrConfigServiceGetPoolsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDistrConfigServiceGetPoolsParamsWithTimeout(timeout time.Duration) *DistrConfigServiceGetPoolsParams {

	return &DistrConfigServiceGetPoolsParams{

		timeout: timeout,
	}
}

// NewDistrConfigServiceGetPoolsParamsWithContext creates a new DistrConfigServiceGetPoolsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDistrConfigServiceGetPoolsParamsWithContext(ctx context.Context) *DistrConfigServiceGetPoolsParams {

	return &DistrConfigServiceGetPoolsParams{

		Context: ctx,
	}
}

// NewDistrConfigServiceGetPoolsParamsWithHTTPClient creates a new DistrConfigServiceGetPoolsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDistrConfigServiceGetPoolsParamsWithHTTPClient(client *http.Client) *DistrConfigServiceGetPoolsParams {

	return &DistrConfigServiceGetPoolsParams{
		HTTPClient: client,
	}
}

/*DistrConfigServiceGetPoolsParams contains all the parameters to send to the API endpoint
for the distr config service get pools operation typically these are written to a http.Request
*/
type DistrConfigServiceGetPoolsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the distr config service get pools params
func (o *DistrConfigServiceGetPoolsParams) WithTimeout(timeout time.Duration) *DistrConfigServiceGetPoolsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the distr config service get pools params
func (o *DistrConfigServiceGetPoolsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the distr config service get pools params
func (o *DistrConfigServiceGetPoolsParams) WithContext(ctx context.Context) *DistrConfigServiceGetPoolsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the distr config service get pools params
func (o *DistrConfigServiceGetPoolsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the distr config service get pools params
func (o *DistrConfigServiceGetPoolsParams) WithHTTPClient(client *http.Client) *DistrConfigServiceGetPoolsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the distr config service get pools params
func (o *DistrConfigServiceGetPoolsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DistrConfigServiceGetPoolsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
