// Code generated by go-swagger; DO NOT EDIT.

package distr_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// DistrConfigServiceCreateAppReader is a Reader for the DistrConfigServiceCreateApp structure.
type DistrConfigServiceCreateAppReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DistrConfigServiceCreateAppReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDistrConfigServiceCreateAppOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDistrConfigServiceCreateAppNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDistrConfigServiceCreateAppDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDistrConfigServiceCreateAppOK creates a DistrConfigServiceCreateAppOK with default headers values
func NewDistrConfigServiceCreateAppOK() *DistrConfigServiceCreateAppOK {
	return &DistrConfigServiceCreateAppOK{}
}

/*DistrConfigServiceCreateAppOK handles this case with default header values.

A successful response.
*/
type DistrConfigServiceCreateAppOK struct {
	Payload models.DistrconfigCreateAppResponse
}

func (o *DistrConfigServiceCreateAppOK) Error() string {
	return fmt.Sprintf("[POST /api/distribution/v1/app][%d] distrConfigServiceCreateAppOK  %+v", 200, o.Payload)
}

func (o *DistrConfigServiceCreateAppOK) GetPayload() models.DistrconfigCreateAppResponse {
	return o.Payload
}

func (o *DistrConfigServiceCreateAppOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDistrConfigServiceCreateAppNotFound creates a DistrConfigServiceCreateAppNotFound with default headers values
func NewDistrConfigServiceCreateAppNotFound() *DistrConfigServiceCreateAppNotFound {
	return &DistrConfigServiceCreateAppNotFound{}
}

/*DistrConfigServiceCreateAppNotFound handles this case with default header values.

Returned when the resource does not exist.
*/
type DistrConfigServiceCreateAppNotFound struct {
	Payload string
}

func (o *DistrConfigServiceCreateAppNotFound) Error() string {
	return fmt.Sprintf("[POST /api/distribution/v1/app][%d] distrConfigServiceCreateAppNotFound  %+v", 404, o.Payload)
}

func (o *DistrConfigServiceCreateAppNotFound) GetPayload() string {
	return o.Payload
}

func (o *DistrConfigServiceCreateAppNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDistrConfigServiceCreateAppDefault creates a DistrConfigServiceCreateAppDefault with default headers values
func NewDistrConfigServiceCreateAppDefault(code int) *DistrConfigServiceCreateAppDefault {
	return &DistrConfigServiceCreateAppDefault{
		_statusCode: code,
	}
}

/*DistrConfigServiceCreateAppDefault handles this case with default header values.

An unexpected error response
*/
type DistrConfigServiceCreateAppDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the distr config service create app default response
func (o *DistrConfigServiceCreateAppDefault) Code() int {
	return o._statusCode
}

func (o *DistrConfigServiceCreateAppDefault) Error() string {
	return fmt.Sprintf("[POST /api/distribution/v1/app][%d] DistrConfigService_CreateApp default  %+v", o._statusCode, o.Payload)
}

func (o *DistrConfigServiceCreateAppDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *DistrConfigServiceCreateAppDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
