// Code generated by go-swagger; DO NOT EDIT.

package appscape_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// NewAppscapeServiceQueryMetricsParams creates a new AppscapeServiceQueryMetricsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAppscapeServiceQueryMetricsParams() *AppscapeServiceQueryMetricsParams {
	return &AppscapeServiceQueryMetricsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAppscapeServiceQueryMetricsParamsWithTimeout creates a new AppscapeServiceQueryMetricsParams object
// with the ability to set a timeout on a request.
func NewAppscapeServiceQueryMetricsParamsWithTimeout(timeout time.Duration) *AppscapeServiceQueryMetricsParams {
	return &AppscapeServiceQueryMetricsParams{
		timeout: timeout,
	}
}

// NewAppscapeServiceQueryMetricsParamsWithContext creates a new AppscapeServiceQueryMetricsParams object
// with the ability to set a context for a request.
func NewAppscapeServiceQueryMetricsParamsWithContext(ctx context.Context) *AppscapeServiceQueryMetricsParams {
	return &AppscapeServiceQueryMetricsParams{
		Context: ctx,
	}
}

// NewAppscapeServiceQueryMetricsParamsWithHTTPClient creates a new AppscapeServiceQueryMetricsParams object
// with the ability to set a custom HTTPClient for a request.
func NewAppscapeServiceQueryMetricsParamsWithHTTPClient(client *http.Client) *AppscapeServiceQueryMetricsParams {
	return &AppscapeServiceQueryMetricsParams{
		HTTPClient: client,
	}
}

/* AppscapeServiceQueryMetricsParams contains all the parameters to send to the API endpoint
   for the appscape service query metrics operation.

   Typically these are written to a http.Request.
*/
type AppscapeServiceQueryMetricsParams struct {

	// Body.
	Body *models.V1QueryMetricsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the appscape service query metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AppscapeServiceQueryMetricsParams) WithDefaults() *AppscapeServiceQueryMetricsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the appscape service query metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AppscapeServiceQueryMetricsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the appscape service query metrics params
func (o *AppscapeServiceQueryMetricsParams) WithTimeout(timeout time.Duration) *AppscapeServiceQueryMetricsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the appscape service query metrics params
func (o *AppscapeServiceQueryMetricsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the appscape service query metrics params
func (o *AppscapeServiceQueryMetricsParams) WithContext(ctx context.Context) *AppscapeServiceQueryMetricsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the appscape service query metrics params
func (o *AppscapeServiceQueryMetricsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the appscape service query metrics params
func (o *AppscapeServiceQueryMetricsParams) WithHTTPClient(client *http.Client) *AppscapeServiceQueryMetricsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the appscape service query metrics params
func (o *AppscapeServiceQueryMetricsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the appscape service query metrics params
func (o *AppscapeServiceQueryMetricsParams) WithBody(body *models.V1QueryMetricsRequest) *AppscapeServiceQueryMetricsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the appscape service query metrics params
func (o *AppscapeServiceQueryMetricsParams) SetBody(body *models.V1QueryMetricsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AppscapeServiceQueryMetricsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
