// Code generated by go-swagger; DO NOT EDIT.

package auth_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// AuthServiceGetRoleReader is a Reader for the AuthServiceGetRole structure.
type AuthServiceGetRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthServiceGetRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAuthServiceGetRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewAuthServiceGetRoleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewAuthServiceGetRoleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAuthServiceGetRoleOK creates a AuthServiceGetRoleOK with default headers values
func NewAuthServiceGetRoleOK() *AuthServiceGetRoleOK {
	return &AuthServiceGetRoleOK{}
}

/*AuthServiceGetRoleOK handles this case with default header values.

A successful response.
*/
type AuthServiceGetRoleOK struct {
	Payload *models.V1GetRoleResponse
}

func (o *AuthServiceGetRoleOK) Error() string {
	return fmt.Sprintf("[GET /api/auth/v1/role/{roleID}][%d] authServiceGetRoleOK  %+v", 200, o.Payload)
}

func (o *AuthServiceGetRoleOK) GetPayload() *models.V1GetRoleResponse {
	return o.Payload
}

func (o *AuthServiceGetRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetRoleResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuthServiceGetRoleNotFound creates a AuthServiceGetRoleNotFound with default headers values
func NewAuthServiceGetRoleNotFound() *AuthServiceGetRoleNotFound {
	return &AuthServiceGetRoleNotFound{}
}

/*AuthServiceGetRoleNotFound handles this case with default header values.

Returned when the resource does not exist.
*/
type AuthServiceGetRoleNotFound struct {
	Payload string
}

func (o *AuthServiceGetRoleNotFound) Error() string {
	return fmt.Sprintf("[GET /api/auth/v1/role/{roleID}][%d] authServiceGetRoleNotFound  %+v", 404, o.Payload)
}

func (o *AuthServiceGetRoleNotFound) GetPayload() string {
	return o.Payload
}

func (o *AuthServiceGetRoleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuthServiceGetRoleDefault creates a AuthServiceGetRoleDefault with default headers values
func NewAuthServiceGetRoleDefault(code int) *AuthServiceGetRoleDefault {
	return &AuthServiceGetRoleDefault{
		_statusCode: code,
	}
}

/*AuthServiceGetRoleDefault handles this case with default header values.

An unexpected error response
*/
type AuthServiceGetRoleDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the auth service get role default response
func (o *AuthServiceGetRoleDefault) Code() int {
	return o._statusCode
}

func (o *AuthServiceGetRoleDefault) Error() string {
	return fmt.Sprintf("[GET /api/auth/v1/role/{roleID}][%d] AuthService_GetRole default  %+v", o._statusCode, o.Payload)
}

func (o *AuthServiceGetRoleDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *AuthServiceGetRoleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
