// Code generated by go-swagger; DO NOT EDIT.

package auth_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// AuthServiceAddPoliciesToRoleReader is a Reader for the AuthServiceAddPoliciesToRole structure.
type AuthServiceAddPoliciesToRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthServiceAddPoliciesToRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAuthServiceAddPoliciesToRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewAuthServiceAddPoliciesToRoleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewAuthServiceAddPoliciesToRoleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAuthServiceAddPoliciesToRoleOK creates a AuthServiceAddPoliciesToRoleOK with default headers values
func NewAuthServiceAddPoliciesToRoleOK() *AuthServiceAddPoliciesToRoleOK {
	return &AuthServiceAddPoliciesToRoleOK{}
}

/* AuthServiceAddPoliciesToRoleOK describes a response with status code 200, with default header values.

A successful response.
*/
type AuthServiceAddPoliciesToRoleOK struct {
	Payload *models.V1AddPoliciesToRoleResponse
}

func (o *AuthServiceAddPoliciesToRoleOK) Error() string {
	return fmt.Sprintf("[POST /api/auth/v1/role/policies/add][%d] authServiceAddPoliciesToRoleOK  %+v", 200, o.Payload)
}
func (o *AuthServiceAddPoliciesToRoleOK) GetPayload() *models.V1AddPoliciesToRoleResponse {
	return o.Payload
}

func (o *AuthServiceAddPoliciesToRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1AddPoliciesToRoleResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuthServiceAddPoliciesToRoleNotFound creates a AuthServiceAddPoliciesToRoleNotFound with default headers values
func NewAuthServiceAddPoliciesToRoleNotFound() *AuthServiceAddPoliciesToRoleNotFound {
	return &AuthServiceAddPoliciesToRoleNotFound{}
}

/* AuthServiceAddPoliciesToRoleNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type AuthServiceAddPoliciesToRoleNotFound struct {
	Payload string
}

func (o *AuthServiceAddPoliciesToRoleNotFound) Error() string {
	return fmt.Sprintf("[POST /api/auth/v1/role/policies/add][%d] authServiceAddPoliciesToRoleNotFound  %+v", 404, o.Payload)
}
func (o *AuthServiceAddPoliciesToRoleNotFound) GetPayload() string {
	return o.Payload
}

func (o *AuthServiceAddPoliciesToRoleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuthServiceAddPoliciesToRoleDefault creates a AuthServiceAddPoliciesToRoleDefault with default headers values
func NewAuthServiceAddPoliciesToRoleDefault(code int) *AuthServiceAddPoliciesToRoleDefault {
	return &AuthServiceAddPoliciesToRoleDefault{
		_statusCode: code,
	}
}

/* AuthServiceAddPoliciesToRoleDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type AuthServiceAddPoliciesToRoleDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the auth service add policies to role default response
func (o *AuthServiceAddPoliciesToRoleDefault) Code() int {
	return o._statusCode
}

func (o *AuthServiceAddPoliciesToRoleDefault) Error() string {
	return fmt.Sprintf("[POST /api/auth/v1/role/policies/add][%d] AuthService_AddPoliciesToRole default  %+v", o._statusCode, o.Payload)
}
func (o *AuthServiceAddPoliciesToRoleDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *AuthServiceAddPoliciesToRoleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
