// Code generated by go-swagger; DO NOT EDIT.

package auth_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAuthServiceGetUsersForRoleParams creates a new AuthServiceGetUsersForRoleParams object
// with the default values initialized.
func NewAuthServiceGetUsersForRoleParams() *AuthServiceGetUsersForRoleParams {
	var ()
	return &AuthServiceGetUsersForRoleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAuthServiceGetUsersForRoleParamsWithTimeout creates a new AuthServiceGetUsersForRoleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAuthServiceGetUsersForRoleParamsWithTimeout(timeout time.Duration) *AuthServiceGetUsersForRoleParams {
	var ()
	return &AuthServiceGetUsersForRoleParams{

		timeout: timeout,
	}
}

// NewAuthServiceGetUsersForRoleParamsWithContext creates a new AuthServiceGetUsersForRoleParams object
// with the default values initialized, and the ability to set a context for a request
func NewAuthServiceGetUsersForRoleParamsWithContext(ctx context.Context) *AuthServiceGetUsersForRoleParams {
	var ()
	return &AuthServiceGetUsersForRoleParams{

		Context: ctx,
	}
}

// NewAuthServiceGetUsersForRoleParamsWithHTTPClient creates a new AuthServiceGetUsersForRoleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAuthServiceGetUsersForRoleParamsWithHTTPClient(client *http.Client) *AuthServiceGetUsersForRoleParams {
	var ()
	return &AuthServiceGetUsersForRoleParams{
		HTTPClient: client,
	}
}

/*AuthServiceGetUsersForRoleParams contains all the parameters to send to the API endpoint
for the auth service get users for role operation typically these are written to a http.Request
*/
type AuthServiceGetUsersForRoleParams struct {

	/*Limit*/
	Limit *string
	/*Offset*/
	Offset *string
	/*RoleID*/
	RoleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the auth service get users for role params
func (o *AuthServiceGetUsersForRoleParams) WithTimeout(timeout time.Duration) *AuthServiceGetUsersForRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the auth service get users for role params
func (o *AuthServiceGetUsersForRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the auth service get users for role params
func (o *AuthServiceGetUsersForRoleParams) WithContext(ctx context.Context) *AuthServiceGetUsersForRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the auth service get users for role params
func (o *AuthServiceGetUsersForRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the auth service get users for role params
func (o *AuthServiceGetUsersForRoleParams) WithHTTPClient(client *http.Client) *AuthServiceGetUsersForRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the auth service get users for role params
func (o *AuthServiceGetUsersForRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the auth service get users for role params
func (o *AuthServiceGetUsersForRoleParams) WithLimit(limit *string) *AuthServiceGetUsersForRoleParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the auth service get users for role params
func (o *AuthServiceGetUsersForRoleParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithOffset adds the offset to the auth service get users for role params
func (o *AuthServiceGetUsersForRoleParams) WithOffset(offset *string) *AuthServiceGetUsersForRoleParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the auth service get users for role params
func (o *AuthServiceGetUsersForRoleParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WithRoleID adds the roleID to the auth service get users for role params
func (o *AuthServiceGetUsersForRoleParams) WithRoleID(roleID string) *AuthServiceGetUsersForRoleParams {
	o.SetRoleID(roleID)
	return o
}

// SetRoleID adds the roleId to the auth service get users for role params
func (o *AuthServiceGetUsersForRoleParams) SetRoleID(roleID string) {
	o.RoleID = roleID
}

// WriteToRequest writes these params to a swagger request
func (o *AuthServiceGetUsersForRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit string
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	// path param roleID
	if err := r.SetPathParam("roleID", o.RoleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
