// Code generated by go-swagger; DO NOT EDIT.

package auth_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// AuthServiceRemovePoliciesFromRoleReader is a Reader for the AuthServiceRemovePoliciesFromRole structure.
type AuthServiceRemovePoliciesFromRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthServiceRemovePoliciesFromRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAuthServiceRemovePoliciesFromRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewAuthServiceRemovePoliciesFromRoleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewAuthServiceRemovePoliciesFromRoleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAuthServiceRemovePoliciesFromRoleOK creates a AuthServiceRemovePoliciesFromRoleOK with default headers values
func NewAuthServiceRemovePoliciesFromRoleOK() *AuthServiceRemovePoliciesFromRoleOK {
	return &AuthServiceRemovePoliciesFromRoleOK{}
}

/* AuthServiceRemovePoliciesFromRoleOK describes a response with status code 200, with default header values.

A successful response.
*/
type AuthServiceRemovePoliciesFromRoleOK struct {
	Payload *models.V1RemovePoliciesFromRoleResponse
}

func (o *AuthServiceRemovePoliciesFromRoleOK) Error() string {
	return fmt.Sprintf("[POST /api/auth/v1/role/policies/remove][%d] authServiceRemovePoliciesFromRoleOK  %+v", 200, o.Payload)
}
func (o *AuthServiceRemovePoliciesFromRoleOK) GetPayload() *models.V1RemovePoliciesFromRoleResponse {
	return o.Payload
}

func (o *AuthServiceRemovePoliciesFromRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1RemovePoliciesFromRoleResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuthServiceRemovePoliciesFromRoleNotFound creates a AuthServiceRemovePoliciesFromRoleNotFound with default headers values
func NewAuthServiceRemovePoliciesFromRoleNotFound() *AuthServiceRemovePoliciesFromRoleNotFound {
	return &AuthServiceRemovePoliciesFromRoleNotFound{}
}

/* AuthServiceRemovePoliciesFromRoleNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type AuthServiceRemovePoliciesFromRoleNotFound struct {
	Payload string
}

func (o *AuthServiceRemovePoliciesFromRoleNotFound) Error() string {
	return fmt.Sprintf("[POST /api/auth/v1/role/policies/remove][%d] authServiceRemovePoliciesFromRoleNotFound  %+v", 404, o.Payload)
}
func (o *AuthServiceRemovePoliciesFromRoleNotFound) GetPayload() string {
	return o.Payload
}

func (o *AuthServiceRemovePoliciesFromRoleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuthServiceRemovePoliciesFromRoleDefault creates a AuthServiceRemovePoliciesFromRoleDefault with default headers values
func NewAuthServiceRemovePoliciesFromRoleDefault(code int) *AuthServiceRemovePoliciesFromRoleDefault {
	return &AuthServiceRemovePoliciesFromRoleDefault{
		_statusCode: code,
	}
}

/* AuthServiceRemovePoliciesFromRoleDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type AuthServiceRemovePoliciesFromRoleDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the auth service remove policies from role default response
func (o *AuthServiceRemovePoliciesFromRoleDefault) Code() int {
	return o._statusCode
}

func (o *AuthServiceRemovePoliciesFromRoleDefault) Error() string {
	return fmt.Sprintf("[POST /api/auth/v1/role/policies/remove][%d] AuthService_RemovePoliciesFromRole default  %+v", o._statusCode, o.Payload)
}
func (o *AuthServiceRemovePoliciesFromRoleDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *AuthServiceRemovePoliciesFromRoleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
