// Code generated by go-swagger; DO NOT EDIT.

package auth_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// NewAuthServiceUpdateRoleParams creates a new AuthServiceUpdateRoleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAuthServiceUpdateRoleParams() *AuthServiceUpdateRoleParams {
	return &AuthServiceUpdateRoleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAuthServiceUpdateRoleParamsWithTimeout creates a new AuthServiceUpdateRoleParams object
// with the ability to set a timeout on a request.
func NewAuthServiceUpdateRoleParamsWithTimeout(timeout time.Duration) *AuthServiceUpdateRoleParams {
	return &AuthServiceUpdateRoleParams{
		timeout: timeout,
	}
}

// NewAuthServiceUpdateRoleParamsWithContext creates a new AuthServiceUpdateRoleParams object
// with the ability to set a context for a request.
func NewAuthServiceUpdateRoleParamsWithContext(ctx context.Context) *AuthServiceUpdateRoleParams {
	return &AuthServiceUpdateRoleParams{
		Context: ctx,
	}
}

// NewAuthServiceUpdateRoleParamsWithHTTPClient creates a new AuthServiceUpdateRoleParams object
// with the ability to set a custom HTTPClient for a request.
func NewAuthServiceUpdateRoleParamsWithHTTPClient(client *http.Client) *AuthServiceUpdateRoleParams {
	return &AuthServiceUpdateRoleParams{
		HTTPClient: client,
	}
}

/* AuthServiceUpdateRoleParams contains all the parameters to send to the API endpoint
   for the auth service update role operation.

   Typically these are written to a http.Request.
*/
type AuthServiceUpdateRoleParams struct {

	// Body.
	Body *models.V1UpdateRoleRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the auth service update role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthServiceUpdateRoleParams) WithDefaults() *AuthServiceUpdateRoleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the auth service update role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthServiceUpdateRoleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the auth service update role params
func (o *AuthServiceUpdateRoleParams) WithTimeout(timeout time.Duration) *AuthServiceUpdateRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the auth service update role params
func (o *AuthServiceUpdateRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the auth service update role params
func (o *AuthServiceUpdateRoleParams) WithContext(ctx context.Context) *AuthServiceUpdateRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the auth service update role params
func (o *AuthServiceUpdateRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the auth service update role params
func (o *AuthServiceUpdateRoleParams) WithHTTPClient(client *http.Client) *AuthServiceUpdateRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the auth service update role params
func (o *AuthServiceUpdateRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the auth service update role params
func (o *AuthServiceUpdateRoleParams) WithBody(body *models.V1UpdateRoleRequest) *AuthServiceUpdateRoleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the auth service update role params
func (o *AuthServiceUpdateRoleParams) SetBody(body *models.V1UpdateRoleRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AuthServiceUpdateRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
