// Code generated by go-swagger; DO NOT EDIT.

package auth_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// NewAuthServiceCreateUserParams creates a new AuthServiceCreateUserParams object
// with the default values initialized.
func NewAuthServiceCreateUserParams() *AuthServiceCreateUserParams {
	var ()
	return &AuthServiceCreateUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAuthServiceCreateUserParamsWithTimeout creates a new AuthServiceCreateUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAuthServiceCreateUserParamsWithTimeout(timeout time.Duration) *AuthServiceCreateUserParams {
	var ()
	return &AuthServiceCreateUserParams{

		timeout: timeout,
	}
}

// NewAuthServiceCreateUserParamsWithContext creates a new AuthServiceCreateUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewAuthServiceCreateUserParamsWithContext(ctx context.Context) *AuthServiceCreateUserParams {
	var ()
	return &AuthServiceCreateUserParams{

		Context: ctx,
	}
}

// NewAuthServiceCreateUserParamsWithHTTPClient creates a new AuthServiceCreateUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAuthServiceCreateUserParamsWithHTTPClient(client *http.Client) *AuthServiceCreateUserParams {
	var ()
	return &AuthServiceCreateUserParams{
		HTTPClient: client,
	}
}

/*AuthServiceCreateUserParams contains all the parameters to send to the API endpoint
for the auth service create user operation typically these are written to a http.Request
*/
type AuthServiceCreateUserParams struct {

	/*Body*/
	Body *models.V1CreateUserRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the auth service create user params
func (o *AuthServiceCreateUserParams) WithTimeout(timeout time.Duration) *AuthServiceCreateUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the auth service create user params
func (o *AuthServiceCreateUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the auth service create user params
func (o *AuthServiceCreateUserParams) WithContext(ctx context.Context) *AuthServiceCreateUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the auth service create user params
func (o *AuthServiceCreateUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the auth service create user params
func (o *AuthServiceCreateUserParams) WithHTTPClient(client *http.Client) *AuthServiceCreateUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the auth service create user params
func (o *AuthServiceCreateUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the auth service create user params
func (o *AuthServiceCreateUserParams) WithBody(body *models.V1CreateUserRequest) *AuthServiceCreateUserParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the auth service create user params
func (o *AuthServiceCreateUserParams) SetBody(body *models.V1CreateUserRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AuthServiceCreateUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
