// Code generated by go-swagger; DO NOT EDIT.

package auth_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAuthServiceGetUserParams creates a new AuthServiceGetUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAuthServiceGetUserParams() *AuthServiceGetUserParams {
	return &AuthServiceGetUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAuthServiceGetUserParamsWithTimeout creates a new AuthServiceGetUserParams object
// with the ability to set a timeout on a request.
func NewAuthServiceGetUserParamsWithTimeout(timeout time.Duration) *AuthServiceGetUserParams {
	return &AuthServiceGetUserParams{
		timeout: timeout,
	}
}

// NewAuthServiceGetUserParamsWithContext creates a new AuthServiceGetUserParams object
// with the ability to set a context for a request.
func NewAuthServiceGetUserParamsWithContext(ctx context.Context) *AuthServiceGetUserParams {
	return &AuthServiceGetUserParams{
		Context: ctx,
	}
}

// NewAuthServiceGetUserParamsWithHTTPClient creates a new AuthServiceGetUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewAuthServiceGetUserParamsWithHTTPClient(client *http.Client) *AuthServiceGetUserParams {
	return &AuthServiceGetUserParams{
		HTTPClient: client,
	}
}

/* AuthServiceGetUserParams contains all the parameters to send to the API endpoint
   for the auth service get user operation.

   Typically these are written to a http.Request.
*/
type AuthServiceGetUserParams struct {

	// UserID.
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the auth service get user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthServiceGetUserParams) WithDefaults() *AuthServiceGetUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the auth service get user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthServiceGetUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the auth service get user params
func (o *AuthServiceGetUserParams) WithTimeout(timeout time.Duration) *AuthServiceGetUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the auth service get user params
func (o *AuthServiceGetUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the auth service get user params
func (o *AuthServiceGetUserParams) WithContext(ctx context.Context) *AuthServiceGetUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the auth service get user params
func (o *AuthServiceGetUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the auth service get user params
func (o *AuthServiceGetUserParams) WithHTTPClient(client *http.Client) *AuthServiceGetUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the auth service get user params
func (o *AuthServiceGetUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the auth service get user params
func (o *AuthServiceGetUserParams) WithUserID(userID string) *AuthServiceGetUserParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the auth service get user params
func (o *AuthServiceGetUserParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *AuthServiceGetUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param userID
	if err := r.SetPathParam("userID", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
