// Code generated by go-swagger; DO NOT EDIT.

package auth_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zestlabs-io/zest-go-sdk/api/models"
)

// NewAuthServiceUpdateAccountParams creates a new AuthServiceUpdateAccountParams object
// with the default values initialized.
func NewAuthServiceUpdateAccountParams() *AuthServiceUpdateAccountParams {
	var ()
	return &AuthServiceUpdateAccountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAuthServiceUpdateAccountParamsWithTimeout creates a new AuthServiceUpdateAccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAuthServiceUpdateAccountParamsWithTimeout(timeout time.Duration) *AuthServiceUpdateAccountParams {
	var ()
	return &AuthServiceUpdateAccountParams{

		timeout: timeout,
	}
}

// NewAuthServiceUpdateAccountParamsWithContext creates a new AuthServiceUpdateAccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewAuthServiceUpdateAccountParamsWithContext(ctx context.Context) *AuthServiceUpdateAccountParams {
	var ()
	return &AuthServiceUpdateAccountParams{

		Context: ctx,
	}
}

// NewAuthServiceUpdateAccountParamsWithHTTPClient creates a new AuthServiceUpdateAccountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAuthServiceUpdateAccountParamsWithHTTPClient(client *http.Client) *AuthServiceUpdateAccountParams {
	var ()
	return &AuthServiceUpdateAccountParams{
		HTTPClient: client,
	}
}

/*AuthServiceUpdateAccountParams contains all the parameters to send to the API endpoint
for the auth service update account operation typically these are written to a http.Request
*/
type AuthServiceUpdateAccountParams struct {

	/*AccountAccountID*/
	AccountAccountID string
	/*Body*/
	Body *models.V1UpdateAccountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the auth service update account params
func (o *AuthServiceUpdateAccountParams) WithTimeout(timeout time.Duration) *AuthServiceUpdateAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the auth service update account params
func (o *AuthServiceUpdateAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the auth service update account params
func (o *AuthServiceUpdateAccountParams) WithContext(ctx context.Context) *AuthServiceUpdateAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the auth service update account params
func (o *AuthServiceUpdateAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the auth service update account params
func (o *AuthServiceUpdateAccountParams) WithHTTPClient(client *http.Client) *AuthServiceUpdateAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the auth service update account params
func (o *AuthServiceUpdateAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountAccountID adds the accountAccountID to the auth service update account params
func (o *AuthServiceUpdateAccountParams) WithAccountAccountID(accountAccountID string) *AuthServiceUpdateAccountParams {
	o.SetAccountAccountID(accountAccountID)
	return o
}

// SetAccountAccountID adds the accountAccountId to the auth service update account params
func (o *AuthServiceUpdateAccountParams) SetAccountAccountID(accountAccountID string) {
	o.AccountAccountID = accountAccountID
}

// WithBody adds the body to the auth service update account params
func (o *AuthServiceUpdateAccountParams) WithBody(body *models.V1UpdateAccountRequest) *AuthServiceUpdateAccountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the auth service update account params
func (o *AuthServiceUpdateAccountParams) SetBody(body *models.V1UpdateAccountRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AuthServiceUpdateAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account.accountID
	if err := r.SetPathParam("account.accountID", o.AccountAccountID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
