// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DataGetResponse data get response
//
// swagger:model dataGetResponse
type DataGetResponse struct {
	DataDocument
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *DataGetResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 DataDocument
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.DataDocument = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m DataGetResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.DataDocument)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this data get response
func (m *DataGetResponse) Validate(formats strfmt.Registry) error {
	return nil
}
