// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DataPersistResponse data persist response
//
// swagger:model dataPersistResponse
type DataPersistResponse struct {

	// id
	ID string `json:"id,omitempty"`

	// rev
	Rev string `json:"rev,omitempty"`
}

// Validate validates this data persist response
func (m *DataPersistResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DataPersistResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataPersistResponse) UnmarshalBinary(b []byte) error {
	var res DataPersistResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
