// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DistrconfigCreateUserRequest distrconfig create user request
//
// swagger:model distrconfigCreateUserRequest
type DistrconfigCreateUserRequest struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this distrconfig create user request
func (m *DistrconfigCreateUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this distrconfig create user request based on context it is used
func (m *DistrconfigCreateUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DistrconfigCreateUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DistrconfigCreateUserRequest) UnmarshalBinary(b []byte) error {
	var res DistrconfigCreateUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
