// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DistrconfigMobileAppWithPools distrconfig mobile app with pools
//
// swagger:model distrconfigMobileAppWithPools
type DistrconfigMobileAppWithPools struct {

	// active
	Active bool `json:"active,omitempty"`

	// assigned pools
	AssignedPools []string `json:"assignedPools"`

	// bundle Url
	BundleURL string `json:"bundleUrl,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this distrconfig mobile app with pools
func (m *DistrconfigMobileAppWithPools) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this distrconfig mobile app with pools based on context it is used
func (m *DistrconfigMobileAppWithPools) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DistrconfigMobileAppWithPools) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DistrconfigMobileAppWithPools) UnmarshalBinary(b []byte) error {
	var res DistrconfigMobileAppWithPools
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
