// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DistrconfigMobileApp distrconfig mobile app
//
// swagger:model distrconfigMobileApp
type DistrconfigMobileApp struct {

	// active
	Active bool `json:"active,omitempty"`

	// Bundle URL for downloading the react bundle
	BundleURL string `json:"bundleUrl,omitempty"`

	// Primary key - unique by account
	ID string `json:"id,omitempty"`
}

// Validate validates this distrconfig mobile app
func (m *DistrconfigMobileApp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this distrconfig mobile app based on context it is used
func (m *DistrconfigMobileApp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DistrconfigMobileApp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DistrconfigMobileApp) UnmarshalBinary(b []byte) error {
	var res DistrconfigMobileApp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
