// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FunctionsCreateFunctionResponse functions create function response
//
// swagger:model functionsCreateFunctionResponse
type FunctionsCreateFunctionResponse struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this functions create function response
func (m *FunctionsCreateFunctionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FunctionsCreateFunctionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FunctionsCreateFunctionResponse) UnmarshalBinary(b []byte) error {
	var res FunctionsCreateFunctionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
