// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1AddPoliciesToUserRequest v1 add policies to user request
//
// swagger:model v1AddPoliciesToUserRequest
type V1AddPoliciesToUserRequest struct {

	// policy i ds
	PolicyIDs []string `json:"policyIDs"`

	// user ID
	UserID string `json:"userID,omitempty"`
}

// Validate validates this v1 add policies to user request
func (m *V1AddPoliciesToUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1AddPoliciesToUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AddPoliciesToUserRequest) UnmarshalBinary(b []byte) error {
	var res V1AddPoliciesToUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
