// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateClientRequest v1 create client request
//
// swagger:model v1CreateClientRequest
type V1CreateClientRequest struct {

	// base color
	BaseColor string `json:"base_color,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// redirect uri
	RedirectURI string `json:"redirect_uri,omitempty"`

	// suffix
	Suffix string `json:"suffix,omitempty"`
}

// Validate validates this v1 create client request
func (m *V1CreateClientRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 create client request based on context it is used
func (m *V1CreateClientRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateClientRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateClientRequest) UnmarshalBinary(b []byte) error {
	var res V1CreateClientRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
