// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CheckTokenAuthRequest v1 check token auth request
//
// swagger:model v1CheckTokenAuthRequest
type V1CheckTokenAuthRequest struct {

	// auth key
	AuthKey string `json:"authKey,omitempty"`

	// signature
	Signature string `json:"signature,omitempty"`

	// validity
	Validity string `json:"validity,omitempty"`
}

// Validate validates this v1 check token auth request
func (m *V1CheckTokenAuthRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1CheckTokenAuthRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CheckTokenAuthRequest) UnmarshalBinary(b []byte) error {
	var res V1CheckTokenAuthRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
