// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateFederationConfigRequest v1 create federation config request
//
// swagger:model v1CreateFederationConfigRequest
type V1CreateFederationConfigRequest struct {

	// fed type
	FedType *V1FederationType `json:"fedType,omitempty"`

	// oidc client ID
	OidcClientID string `json:"oidcClientID,omitempty"`

	// oidc client secret
	OidcClientSecret string `json:"oidcClientSecret,omitempty"`

	// OIDC Config
	OidcEndpoint string `json:"oidcEndpoint,omitempty"`

	// oidc scopes
	OidcScopes string `json:"oidcScopes,omitempty"`

	// oidc use secret
	OidcUseSecret bool `json:"oidcUseSecret,omitempty"`
}

// Validate validates this v1 create federation config request
func (m *V1CreateFederationConfigRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFedType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1CreateFederationConfigRequest) validateFedType(formats strfmt.Registry) error {
	if swag.IsZero(m.FedType) { // not required
		return nil
	}

	if m.FedType != nil {
		if err := m.FedType.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("fedType")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("fedType")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 create federation config request based on the context it is used
func (m *V1CreateFederationConfigRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFedType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1CreateFederationConfigRequest) contextValidateFedType(ctx context.Context, formats strfmt.Registry) error {

	if m.FedType != nil {
		if err := m.FedType.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("fedType")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("fedType")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateFederationConfigRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateFederationConfigRequest) UnmarshalBinary(b []byte) error {
	var res V1CreateFederationConfigRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
