// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1LabelValues LabelValues contain a list of all possible values per label name.
//
// swagger:model v1LabelValues
type V1LabelValues struct {

	// name
	Name string `json:"name,omitempty"`

	// values
	Values []string `json:"values"`
}

// Validate validates this v1 label values
func (m *V1LabelValues) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1LabelValues) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1LabelValues) UnmarshalBinary(b []byte) error {
	var res V1LabelValues
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
