// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1OIDCClient v1 o ID c client
//
// swagger:model v1OIDCClient
type V1OIDCClient struct {

	// base color
	BaseColor string `json:"base_color,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// redirect uri
	RedirectURI string `json:"redirect_uri,omitempty"`

	// secret
	Secret string `json:"secret,omitempty"`
}

// Validate validates this v1 o ID c client
func (m *V1OIDCClient) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 o ID c client based on context it is used
func (m *V1OIDCClient) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1OIDCClient) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1OIDCClient) UnmarshalBinary(b []byte) error {
	var res V1OIDCClient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
