// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1RemoveUsersFromRoleResponse v1 remove users from role response
//
// swagger:model v1RemoveUsersFromRoleResponse
type V1RemoveUsersFromRoleResponse struct {

	// failed user i ds
	FailedUserIDs []string `json:"failedUserIDs"`
}

// Validate validates this v1 remove users from role response
func (m *V1RemoveUsersFromRoleResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1RemoveUsersFromRoleResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1RemoveUsersFromRoleResponse) UnmarshalBinary(b []byte) error {
	var res V1RemoveUsersFromRoleResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
