// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1SetPasswordRequest v1 set password request
//
// swagger:model v1SetPasswordRequest
type V1SetPasswordRequest struct {

	// new password
	NewPassword string `json:"newPassword,omitempty"`

	// user ID
	UserID string `json:"userID,omitempty"`

	// user password
	UserPassword string `json:"userPassword,omitempty"`
}

// Validate validates this v1 set password request
func (m *V1SetPasswordRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1SetPasswordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SetPasswordRequest) UnmarshalBinary(b []byte) error {
	var res V1SetPasswordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
