// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1UserUpdate v1 user update
//
// swagger:model v1UserUpdate
type V1UserUpdate struct {

	// email
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"firstName,omitempty"`

	// language
	Language string `json:"language,omitempty"`

	// last name
	LastName string `json:"lastName,omitempty"`

	// phone number
	PhoneNumber string `json:"phoneNumber,omitempty"`

	// user ID
	UserID string `json:"userID,omitempty"`
}

// Validate validates this v1 user update
func (m *V1UserUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1UserUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1UserUpdate) UnmarshalBinary(b []byte) error {
	var res V1UserUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
